### ISSUE TITLE
Licensing ?

### ISSUE THREAD

**Issue by vigneshbarani24** [DHTMLX/angular-gantt-demo#13]
Can i use this in my SaaS without any hassles ? The Usage in SaaS is a yes as per the 
![image](https://user-images.githubusercontent.com/20842962/55700861-947fc200-59ee-11e9-9d22-47217e2c1c6a.png)

but the license says GPL. 
Help needed on proceeding further

**Comment by AlexKlimenkov** [comment]
Hi,

technically you can use a GPLv2 version for your SaaS, but I can't call it hassle-free in terms of licensing.

If you use it privately (or within the company), without releasing it to the public, you can do with it whatever you want.

If you release or distribute it in some way, the whole app must be published under GPL license which means disclosing source codes to your users.
https://www.gnu.org/licenses/gpl-faq.html#GPLRequireSourcePostedPublic

There are different opinions over the internets whether the network usage as in SaaS counts as distribution. 
This is fruitful ground for debates, but currently, DHTMLX's standing is the following - we talk about client-side javascript. Each time users access the app, the browser downloads the js code of your application, which includes the gantt component, to the client machine in order to run the app. Thus, it's being distributed and must apply GPLv2 terms. 
If you'll going to make a desktop client for your service or give your clients an option for a local installation of the service - it would also be considered as a distribution.

Overall, the intended licenses for SaaS usage are either Enterprise or Ultimate. 
At your discretion, you can use GPL, but the licensing model doesn't especially encourage it.
